Repository juni8453/spring-cafe-jpa, pull requests merged in 2022-05, with the labels that each got.

#14 feat : MVC 기본 구조 작성 및 심플 테스트 (#4)
  src/main/java/jpaproject/cafe/controller/ArticleController.java
  src/main/java/jpaproject/cafe/controller/MemberController.java
  src/main/java/jpaproject/cafe/domain/Article.java
  src/main/java/jpaproject/cafe/domain/Member.java
  src/main/java/jpaproject/cafe/repository/ArticleRepository.java
  src/main/java/jpaproject/cafe/repository/MemberRepository.java
  src/main/java/jpaproject/cafe/service/ArticleService.java
  src/main/java/jpaproject/cafe/service/MemberService.java
  src/test/java/jpaproject/cafe/repository/ArticleRepositoryTest.java
  src/test/java/jpaproject/cafe/repository/MemberRepositoryTest.java
Labels: BE, FEAT

#31 프론트 글쓰기 기능 추가
  .idea/misc.xml
  react/cafe/.gitignore
  react/cafe/.vscode/settings.json
  react/cafe/README.md
  react/cafe/package-lock.json
  react/cafe/package.json
  react/cafe/public/favicon.ico
  react/cafe/public/index.html
  react/cafe/public/logo192.png
  react/cafe/public/logo512.png
  react/cafe/public/manifest.json
  react/cafe/public/robots.txt
  react/cafe/src/App.css
  react/cafe/src/App.js
  react/cafe/src/App.test.js
  react/cafe/src/component/Article.js
  react/cafe/src/component/ArticleList.js
  react/cafe/src/component/CreateArticle.js
  react/cafe/src/component/Header.js
  react/cafe/src/component/UserInfo.js
  react/cafe/src/hook/useFetch.js
  react/cafe/src/index.css
  react/cafe/src/index.js
  react/cafe/src/logo.svg
  react/cafe/src/reportWebVitals.js
  react/cafe/src/setupTests.js
Labels: FEAT, FE

#33 fix :bug:: Patch 요청 시 null 값 처리
  src/main/java/jpaproject/cafe/article/Article.java
  src/main/java/jpaproject/cafe/article/ArticleController.java
  src/main/java/jpaproject/cafe/article/ArticleService.java
  src/main/java/jpaproject/cafe/article/dto/ArticleUpdateDto.java
Labels: BE, FIX
